{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d6aa74cd-7e1c-4487-8a33-2d8bbb3e5e60",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests # ипортируем библиотеку http-запросов\n",
    "\n",
    "class CurrencyConverter:\n",
    "    def __init__(self):\n",
    "        self.rates = self._get_rates()\n",
    "    \n",
    "    def _get_rates(self): # получает курсы валют с API\n",
    "        try:\n",
    "            # получаем курсы относительно RUB\n",
    "            response = requests.get(\"https://api.exchangerate.host/latest?base=RUB\", timeout = 5)\n",
    "            data = response.json()\n",
    "            return data['rates']\n",
    "        except:\n",
    "            # резервные курсы если API недоступно (сколько рублей за 1 единицу валюты)\n",
    "            return {\n",
    "                'USD': 0.0109,  # 1 USD = 91.74 RUB → 1 RUB = 0.0109 USD\n",
    "                'EUR': 0.0101,  # 1 EUR = 99.01 RUB → 1 RUB = 0.0101 EUR\n",
    "                'RUB': 1.0,     # 1 RUB = 1 RUB\n",
    "                'GBP': 0.0086,  # 1 GBP = 116.28 RUB → 1 RUB = 0.0086 GBP\n",
    "                'JPY': 1.61,    # 1 JPY = 0.62 RUB → 1 RUB = 1.61 JPY\n",
    "                'CNY': 0.078,   # 1 CNY = 12.82 RUB → 1 RUB = 0.078 CNY\n",
    "                'KZT': 5.12     # 1 KZT = 0.195 RUB → 1 RUB = 5.12 KZT\n",
    "            }\n",
    "    \n",
    "    def convert(self, amount, from_curr, to_curr):\n",
    "        \"\"\"Конвертирует сумму из одной валюты в другую\"\"\"\n",
    "        from_curr = from_curr.upper()\n",
    "        to_curr = to_curr.upper()\n",
    "        \n",
    "        if from_curr not in self.rates or to_curr not in self.rates:\n",
    "            return None\n",
    "        \n",
    "        # прямая конвертация\n",
    "        rub_amount = amount * self.rates[from_curr]  # переводим в рубли\n",
    "        result = rub_amount / self.rates[to_curr]    # переводим из рублей в целевую валюту\n",
    "        \n",
    "        return round(result, 2)\n",
    "\n",
    "def main():\n",
    "    converter = CurrencyConverter()\n",
    "    \n",
    "    print(\"=== КОНВЕРТЕР ВАЛЮТ ===\")\n",
    "    print(\"Для выхода введите 'exit'\")\n",
    "    print()\n",
    "    print(\"Доступные валюты: RUB, USD, EUR, GBP, JPY, CNY, KZT\")\n",
    "    print(\"\\nПример: 1000 RUB -> USD\")\n",
    "    print()\n",
    "    \n",
    "    while True:\n",
    "        try:\n",
    "            amount_input = input(\"Введите сумму: \")\n",
    "            if amount_input.lower() == 'exit':\n",
    "                break\n",
    "            \n",
    "            amount = float(amount_input)\n",
    "            from_curr = input(\"Из валюты (например RUB): \").strip().upper() or \"RUB\"\n",
    "            to_curr = input(\"В валюту (например USD): \").strip().upper() or \"USD\"\n",
    "            \n",
    "            result = converter.convert(amount, from_curr, to_curr)\n",
    "            \n",
    "            if result is not None:\n",
    "                print(f\"\\n💱 {amount} {from_curr} = {result} {to_curr}\")\n",
    "                print()\n",
    "            else:\n",
    "                print(\"❌ Ошибка: проверьте правильность ввода валют\\n\")\n",
    "                \n",
    "        except ValueError:\n",
    "            print(\"❌ Ошибка: введите корректную сумму\\n\")\n",
    "        except KeyboardInterrupt:\n",
    "            print(\"\\n\\nВыход из программы\")\n",
    "            break\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
